language: haskell
install:
 - bundle install
 - travis_retry cabal install pandoc pandoc-citeproc
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "4uk/plZWj3T4tb6Cg2hLBLEoO9qk9Z9vVDv7SzZ2h0VKsDnd7GcPTy1J8464eFPmvYnpOc6O+ZCxD678aKehJlA24ksF3ZfwJP6don/1+1kHwxxjeOYHDj/dGSpCYJDo/q04qJYGKoQHY1RXnK4H8zQdspVCxatyu+GIyqbfj3pnBQvIIuJdaPcVqXYHmNXcohtKxHpAe4dlQkUnEWx7OzJuHNPa+YzOGCnOs+U41Om7XeD8q5pmJkDsH8pu17K9skE8D7N6SNrZAhcMcFw20LWHW3uWtO2zeF7SH9eL8VDHHacnAuhm9GUhTlYP0JEHgJ4C3uJ6yXddoKKg5d3pVhRBAGHoKF1E7Ybx4aXogW6bzmEFY0G8gvb6+q39t9gW01GsXcYqfMsLuVgpu1+uXXPjYIdBYc8xXhbE0yWpSDTYxo0gPjWoVtO5vxx/kRoc/l5KNYCLFkVxRG/B6hcg9kF458y9vXqcwh0Q3Iy0QVEm1pwJ8oCXixXWhDaouicHc1zj5oXbT2hHMP1749jNeMrXNvzQHliGrQ6V5qViacb509eRr4oo0BcUYzZWDtDjZSkuR0w9OIE5Tp7c0lu66BDFbHZkTq0jFxseAWQElFZSLdyTvoKlvPLwgSzy16hOoQd1j/uKvauOpAhS/ac4WWZEx1yii4Y6KZv5K8gX2gs="