language: haskell
install:
 - bundle install
 - travis_retry cabal install pandoc pandoc-citeproc
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "5eUnI7LdaHHSlKTWph/jnIfYhOqgDSSCz5V/0RG4QnPMkSQGQbRxMyA2X6nK/AsFjtkJR8Ytd5UB+dHq707kRE4jGqJuNTF6vNW1sKnjbeUky5cfnOXBL8N5L40yXmnpt0jmWG6wkaTUX7jKUQQ3wy3mCD7VJkaxvbxQJ/D4aGGjf4BlScYkUHVZTQgks1lykDCRnV60P7HjWiwUvk9du1MHt2fHXb9n2vhCae/Ep+ngVPIFzCv+ewR19jiA9a82JfYTr9+u5TzGDg7pkORMeXT4CiiMKekYX6SVE+wSukunAN6YgCenS/sXz/kC6ZYNBEFZtPQC7CNnHabPJZGjrFV7GX0tv+f3OjitRriZAvneVZP38sOC3EMbh26pEVxEMlHQ1/uFMyKJochC7HtgEiEJpRaylX6uZkxN/TkBf/2PlVPbRkId2KMHeUksh0vhIfdSWcR/iH6rdXQWl0fWVyCYuZqtaa2ypgp4v0TxMpjl7txYnD5h4lt0fK0qJGZWQSP0iIhLe5BkP4moWrLbwVU1EIy11xMh13F0XwDxVaBRs7fGzq42zJYY8i5+fy3blTlhveS/H+Xct1rJS2FdyJXBm8c8pa6MF2c4dVkPARSD6grGYZnqSCypadoNRCRONq2oqiujUqIKa0n/gEO/+d33QAm9vD2SL1VG21002Gg="
