name: 3D Digital Art and Design Open Education Resource
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
baseurl: /3d-digital-art-and-design--oer

gems:
  - jekyll-sitemap
collections:
  lessons:
    output: true
  exercises:
    output: true
  grading:
    output: true
  syllabus:
    output: true
  topics:
    output: true
    

