name: 3D Digital Art and Design Open Education Resource
author: Michael Collins
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
baseurl: /3d-digital-art-and-design--oer
permalink: pretty
gems:
  - jekyll-sitemap
collections:
  lessons:
    output: true
    permalink: /lessons/:title/
  exercises:
    output: true
    permalink: /exercises/:title.html
  grading:
    output: true
    permalink: /:title.html
  syllabus:
    output: true
    permalink: /:title.html
  topics:
    output: true
    permalink: /topics/:title.html