safe: false
lsi: false
pygments: true

relative_source: ../3d-digital-art-and-design--oer/
destination: ../3d-digital-art-and-design--oer/

# Settings for deploy rake task
# github_user: michael-collins
# source_repo: 3d-digital-art-and-design--oer
# destination_repo: 3d-digital-art-and-design--oer

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: michael-collins
repo: 3d-digital-art-and-design--oer
branch: master

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
